name: Code Quality Checker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./github/actions/setup-maven-and-jdk

      - name: Run Checkstyle
        run: mvn checkstyle:check --no-transfer-progress

  spotbugs:
    name: Bug Spotter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./github/actions/setup-maven-and-jdk

      - name: Compile project for SpotBugs
        run: mvn compile --no-transfer-progress

      - name: Run SpotBugs
        run: mvn spotbugs:check --no-transfer-progress

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./github/actions/setup-maven-and-jdk

      - name: Cache NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: nvd-cache-

      - name: Run OWASP Dependency Check
        run: mvn dependency-check:check --no-transfer-progress

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html


